{% set name = "csr" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61128f621b306a8ccc7c0ce6ce61279a55d9bc3e30e9cd4c3bcd7dfd8fc9f557

build:
  number: 1
  skip: true  # [py<37 or python_impl == 'pypy']
  script: |
    # On MKL-supported platforms, we want to make the MKL kernel available
    {{ PYTHON }} build_mkl.py  # [x86_64]
    {{ PYTHON }} -m pip install --no-deps -vv .
  ignore_run_exports:
    - mkl

requirements:
  build:
    # X86-64 needs the dependencies to build the MKL extension
    - {{ compiler('c') }}  # [x86_64]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # - cython                                 # [build_platform != target_platform]
    - numpy >=1.17                           # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - flit-core >=3.2
    - cffi >=1.12.2    # [x86_64]
    - mkl-devel        # [x86_64]
  run:
    - python
    - numba >=0.51
    - numpy >=1.17
    - scipy
    - cffi >=1.12.2    # [x86_64]

test:
  requires:
    - pytest
    - hypothesis
    - pytest-benchmark
    - psutil
    - libblas=*=*mkl   # [x86_64]
  source_files:
    - pytest.ini
    - conftest.py
    - tests
    - tests/*.py
  imports:
    - csr
    - csr.kernel
    # make sure the MKL kernel works on x86-64
    - csr.kernels.mkl  # [x86_64]
  commands:
    # run the tests, but with the lower-overhead Hypothesis profile
    - python -m pytest tests --hypothesis-profile=nojit

about:
  home: https://csr.lenskit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compressed sparse matrices for Python and Numba
  # The remaining entries in this section are optional, but recommended.
  description: |
    CSR is a compressed sparse row sparse matrix package for Python,
    with Numba-accessible APIs and optional MKL acceleration.
  doc_url: https://csr.lenskit.org
  dev_url: https://github.com/lenskit/csr

extra:
  recipe-maintainers:
    - mdekstrand
